name: worker
services:
  server:
    build:
      context: .
      target: final
    ports:
      - 40041:40041
    environment:
      LEADER_ADDR: "host.docker.internal:50051"
      SCHEDULER_ADDR: "host.docker.internal:50052"
      LOCAL_ADDR: "host.docker.internal:40041"
